### ISSUE TITLE
파일 삭제 이벤트 원자성 보장 / 더미 파일 제거 Cron job

### ISSUE THREAD

**Issue by ecsimsw** [ecsimsw/pic-up#31]
### 파일을 직접 삭제하지 않는 이유 

- 다중 파일 삭제 처리에서 사용자가 파일 삭제 시간을 기다릴 필요는 없다고 생각하여 비동기 처리 계획
- 스레드를 통한 비동기 처리 시, 요청마다 추가 스레드가 필요하고 비정상 종료 등 예외 처리가 까다로울 것으로 판단
- 삭제 로직 안에서 파일을 직접 삭제하지 않고 소프트 딜리트, 이후 일정 시간 간격으로 내역을 조회하고 실제 파일 제거 
- 파일 삭제 시간을 사용자가 기다리지 않도록 하면서도, 다른 스레드를 필요하지 않도록 함

#### 1. 응답 속도 개선
- 파일 삭제 (특히 다중 삭제)를 사용자 요청 처리 주기 안에서 처리하지 않아 사용자가 파일이 삭제되는 시간을 기다리지 않도록 한다.

#### 2. 삭제 이벤트 원자성 보장
- 파일 삭제는 DB transaction 과 달리 한번 삭제 처리하면 롤백되지 않는다.
- 삭제 로직 안에서 DB 데이터와 파일을 삭제하는 과정에서 예외가 발생하는 경우, DB는 롤백되지만 파일은 그렇지 않다.
- 트랜잭션을 분리한다고 하더라도 파일 삭제 이벤트와 DB 삭제 처리의 원자성을 지키기는 쉽지 않다.
- 삭제 이벤트를 DB에 우선 기록하여 예외가 발생할 경우 전부 롤백을 가능하게 하는 것으로, 삭제 로직 안에서 DB와 파일 이벤트의 원자성을 보장한다.

#### 3. 업로드에 실패했으나 DB에 메타데이터는 저장된 경우 / Pending, Commit
- S3 업로드는 WAS에서 처리하는 것이 아닌 S3 pre-signed url 을 부여받고 클라이언트에서 처리하게 된다.
- Pre-signed url 발급 요청이 오면 WAS는 이를 업로드 준비 생각하고 DB에 파일 상태를 `비저장 상태`로 기록한다. (Pending)
- 클라이언트에서 정상 업로드를 완료하면 WAS에 이를 알리고 DB 에 기록해둔 파일 상태를 `저장 상태`로 업데이트한다. (Commit)
- 스토리지 업로드에 실패했거나, WAS에 커밋 요청을 실패(ex, 스토리지 사용 공간 초과)하는 경우 DB의 파일 상태는 `비저장 상태` 로 남게되고, 이는 업로드 실패로 판단되어 스케줄러에 의해 스토리지와 DB 모두에서 제거된다. (Rollback)

### 더미 파일 제거 Batch 서비스 모듈 분리
- WAS에서 일정 주기마다 더미 파일을 제거하는 스케줄러가 돌고 있다.
- WAS가 여러개라면 모두 각각 스케줄러가 돌아 의도한 간격으로 스케줄링이 안될 것이다.
- 아예 WAS에서 따로 독립적으로 실행할 수 있으면 어떨까를 고민한다.
- 중복 스케줄링 문제도 없어지고, 스케줄링이 필요할 때 직접 실행하기도 좋을 것 같다.

### 배치 스크립트 Cron 실행 방법
- Kubernetes cronJob 으로 스케줄링한다.
- ConcurrencyPolicy로 동시 처리 스케줄링 회피

``` yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: server-batch
spec:
  schedule: "*/1 * * * *"     # every minute
  concurrencyPolicy: Forbid   # skip if job already exists
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: server-batch
              image: ghcr.io/ecsimsw/picup/server-batch:latest
              imagePullPolicy: IfNotPresent  # check container hub if image not present, 'name+tag+digest'
          restartPolicy: Never
```

**Comment by ecsimsw** [comment]
Application : `https://github.com/ecsimsw/pic-up/blob/main/server-batch/src/main/java/ecsimsw/picup/application/FileDeletionService.java`

Test : `https://github.com/ecsimsw/pic-up/blob/main/server-batch/src/test/java/ecsimsw/picup/integration/DummyFileDeleteScenarioTest.java`

**Comment by ecsimsw** [comment]
``` yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: server-batch
spec:
  schedule: "*/1 * * * *"     # every minute
  concurrencyPolicy: Forbid   # skip if job already exists
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: server-batch
              image: ghcr.io/ecsimsw/picup/server-batch:latest
              imagePullPolicy: IfNotPresent  # check container hub if image not present, 'name+tag+digest'
          restartPolicy: Never
```
